
[asphyxiation]
	#minimum amount of ticks for cant breathe to enable spawning
	minspawnrate = 24000.0
	#maximum amount of ticks for cant breathe to enable spawning
	maxspawnrate = 120000.0
	#best kept very low cause of the multiplying chase feature
	disappeartimer = 600.0
	#0.1 means you look directly at him, 0.7 means general direction, 1 means when he appears in your screen
	lookatsensitivity = 0.5

